dist: xenial

language: python
python:
    - "3.6"

env:
    - SCVERSION="stable"

before_install:
    - sudo apt-get install -y xz-utils

script:
    - python3 -V
    - sudo rm $(command -v shellcheck)
    - wget https://storage.googleapis.com/shellcheck/shellcheck-${SCVERSION}.linux.x86_64.tar.xz
    - tar --xz -xvf shellcheck-${SCVERSION}.linux.x86_64.tar.xz
    - sudo cp shellcheck-${SCVERSION}/shellcheck /usr/bin/
    - shellcheck --version
    - tests/check.sh

notifications:
  email: false
