dist: xenial

language: sh

before_install:
    - sudo apt-get install -y shellcheck

script:
   - shellcheck --version
   - tests/check.sh
  # shellcheck validate
  #- docker run -v "$PWD:/mnt:ro" docker.io/koalaman/shellcheck -x $(find . -path ./mantle -prune -and -path ./ostree-releng-scripts -prune -o -type f -exec grep -l '^#!/usr/bin/env bash' {} \;)

notifications:
  email: false
